name: "Build On macOS"

on: # @see https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events
  push:
    branches: # Array of patterns that match refs/heads
      - master # Push events on master branch
      - dev
    tags:
      - "*"

jobs:
  build: # job id, can be any string
    # Job name is Build And Publish
    name: Build
    # This job runs on Linux
    strategy:
      matrix:
        os: [macOS-latest]
        rust: [stable]
        target: [x86_64-apple-darwin]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        shell: bash
        run: |
          cargo build --release --verbose --target ${{ matrix.target }}
          if [[ -e "target/${{ matrix.target }}/release/etc" ]]; then
            rm -rf "target/${{ matrix.target }}/release/etc";
          fi
          if [[ -e "target/${{ matrix.target }}/release/tools" ]]; then
            rm -rf "target/${{ matrix.target }}/release/tools";
          fi
          cp -rf etc tools "target/${{ matrix.target }}/release"/ ;
          cd "target/${{ matrix.target }}/release/";
          mkdir -p bin;
          if [[ -e wxwork_robotd ]]; then
            cp -f wxwork_robotd bin/wxwork_robotd;
          else
            cp -f wxwork_robotd* bin/;
          fi
          tar -zcvf ${{ matrix.target }}.tar.gz etc bin tools;
          cd ../../..;
          mv -f "target/${{ matrix.target }}/release/${{ matrix.target }}.tar.gz" ./;
      - name: Run tests
        run: |
          cargo test --release --verbose --target ${{ matrix.target }}
